(function () {
  'use strict';

  // Inject API interceptor into page context (required for MV3 to intercept fetch/XHR)
  try {
    const script = document.createElement('script');
    script.src = chrome.runtime.getURL('api-interceptor.js');
    script.onload = function () {
      this.remove();
    };
    (document.head || document.documentElement).appendChild(script);
  } catch (err) {
    console.debug('[Test Recorder] Failed to inject API interceptor:', err);
  }

  let isRecording = false;
  let stepCounter = 0;
  let lastUrl = window.location.href;
  let inputDebounceTimer = null;
  let pendingInputElement = null;
  let pendingInputValue = null;

  const INTERACTIVE_TAGS = new Set([
    'A', 'BUTTON', 'INPUT', 'SELECT', 'TEXTAREA', 'LABEL', 'OPTION', 'SUMMARY'
  ]);

  const INTERACTIVE_ROLES = new Set([
    'button', 'link', 'checkbox', 'radio', 'textbox', 'combobox', 'listbox',
    'menuitem', 'tab', 'switch', 'slider', 'searchbox'
  ]);

  const INJECTED_PAGE_MESSAGE_SOURCE = 'test-case-recorder-page';
  // Must match CONTENT_SCRIPT_MESSAGE_SOURCE in api-interceptor.js — this is the
  // source the page-context interceptor listens for when the content script
  // notifies it about recording state changes. It must be DIFFERENT from
  // INJECTED_PAGE_MESSAGE_SOURCE above (that one is for page -> content script).
  const CONTENT_SCRIPT_MESSAGE_SOURCE = 'test-case-recorder-context';

  function isAutoGeneratedId(id) {
    return /^[:_]|[0-9]{3,}$|ember|react-|ng-|mui-|radix-|:r\d/i.test(id);
  }

  function getDataAttributes(element) {
    const attrs = {};
    if (!element.attributes) return attrs;
    for (const attr of element.attributes) {
      if (attr.name.startsWith('data-')) {
        attrs[attr.name] = attr.value;
      }
    }
    return attrs;
  }

  function trimText(text, max = 50) {
    const t = (text || '').replace(/\s+/g, ' ').trim();
    return t.length > max ? t.slice(0, max) + '…' : t;
  }

  function isUniqueSelector(selector, element) {
    try {
      const matches = document.querySelectorAll(selector);
      return matches.length === 1 && matches[0] === element;
    } catch {
      return false;
    }
  }

  function escapeCssAttr(value) {
    return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  }

  function escapeXPathString(str) {
    if (!str.includes("'")) return `'${str}'`;
    if (!str.includes('"')) return `"${str}"`;
    return `concat('${str.replace(/'/g, "', \"'\", '")}')`;
  }

  function getAbsoluteXPath(element) {
    if (!element || element.nodeType !== Node.ELEMENT_NODE) return '';
    if (element === document.documentElement) return '/html';
    const parts = [];
    let el = element;
    while (el && el.nodeType === Node.ELEMENT_NODE) {
      let index = 1;
      let sibling = el.previousElementSibling;
      while (sibling) {
        if (sibling.tagName === el.tagName) index++;
        sibling = sibling.previousElementSibling;
      }
      const tag = el.tagName.toLowerCase();
      parts.unshift(`${tag}[${index}]`);
      el = el.parentElement;
    }
    return '/' + parts.join('/');
  }

  function getXPathWithText(element) {
    const text = trimText(element.textContent, 30);
    const tag = element.tagName.toLowerCase();
    if (text) {
      return `//${tag}[contains(normalize-space(.), ${escapeXPathString(text)})]`;
    }
    return getAbsoluteXPath(element);
  }

  function getRelativeXPath(element) {
    let anchor = element.parentElement;
    while (anchor && anchor !== document.body) {
      if (anchor.dataset?.testid) {
        return `//*[@data-testid=${escapeXPathString(anchor.dataset.testid)}]//${element.tagName.toLowerCase()}[contains(normalize-space(.), ${escapeXPathString(trimText(element.textContent, 20))})]`;
      }
      if (anchor.id && !isAutoGeneratedId(anchor.id)) {
        const text = trimText(element.textContent, 20);
        if (text) {
          return `//*[@id=${escapeXPathString(anchor.id)}]//${element.tagName.toLowerCase()}[contains(normalize-space(.), ${escapeXPathString(text)})]`;
        }
        return `//*[@id=${escapeXPathString(anchor.id)}]//${element.tagName.toLowerCase()}`;
      }
      anchor = anchor.parentElement;
    }
    const text = trimText(element.textContent, 30);
    if (text) {
      return `//${element.tagName.toLowerCase()}[contains(normalize-space(.), ${escapeXPathString(text)})]`;
    }
    return getAbsoluteXPath(element);
  }

  function buildFullCssPath(element) {
    const parts = [];
    let el = element;
    while (el && el !== document.body && el.nodeType === Node.ELEMENT_NODE) {
      let part = el.tagName.toLowerCase();
      if (el.id && !isAutoGeneratedId(el.id)) {
        part += `#${CSS.escape(el.id)}`;
        parts.unshift(part);
        break;
      }
      const parent = el.parentElement;
      if (parent) {
        const siblings = Array.from(parent.children).filter((c) => c.tagName === el.tagName);
        if (siblings.length > 1) {
          const idx = siblings.indexOf(el) + 1;
          part += `:nth-of-type(${idx})`;
        }
      }
      parts.unshift(part);
      el = el.parentElement;
    }
    return parts.join(' > ');
  }

  function buildUniqueCssSelector(element) {
    if (element.id && !isAutoGeneratedId(element.id)) {
      const sel = `#${CSS.escape(element.id)}`;
      if (isUniqueSelector(sel, element)) return sel;
    }

    const classes = Array.from(element.classList || []).filter(
      (c) => c && !/^ng-|^react-|^css-|^Mui/.test(c) && !/^\d/.test(c)
    );

    if (classes.length) {
      const classSel = element.tagName.toLowerCase() + '.' + classes.map((c) => CSS.escape(c)).join('.');
      if (isUniqueSelector(classSel, element)) return classSel;
    }

    let path = [];
    let el = element;
    while (el && el !== document.body) {
      let segment = el.tagName.toLowerCase();
      if (el.id && !isAutoGeneratedId(el.id)) {
        segment = `#${CSS.escape(el.id)}`;
        path.unshift(segment);
        const full = path.join(' > ');
        if (isUniqueSelector(full, element)) return full;
        break;
      }
      const parent = el.parentElement;
      if (parent) {
        const sameTag = Array.from(parent.children).filter((c) => c.tagName === el.tagName);
        if (sameTag.length > 1) {
          segment += `:nth-of-type(${sameTag.indexOf(el) + 1})`;
        }
      }
      path.unshift(segment);
      const candidate = path.join(' > ');
      if (isUniqueSelector(candidate, element)) return candidate;
      el = el.parentElement;
    }

    return buildFullCssPath(element);
  }

  function generateBestSelector(element) {
    if (element.dataset?.testid) {
      return `[data-testid="${escapeCssAttr(element.dataset.testid)}"]`;
    }
    if (element.dataset?.cy) {
      return `[data-cy="${escapeCssAttr(element.dataset.cy)}"]`;
    }
    if (element.dataset?.test) {
      return `[data-test="${escapeCssAttr(element.dataset.test)}"]`;
    }
    if (element.id && !isAutoGeneratedId(element.id)) {
      return `#${CSS.escape(element.id)}`;
    }
    const ariaLabel = element.getAttribute('aria-label');
    if (ariaLabel) {
      return `[aria-label="${escapeCssAttr(ariaLabel)}"]`;
    }
    if (element.name) {
      return `${element.tagName.toLowerCase()}[name="${escapeCssAttr(element.name)}"]`;
    }
    const placeholder = element.getAttribute('placeholder');
    if (placeholder && ['INPUT', 'TEXTAREA'].includes(element.tagName)) {
      const phSel = `${element.tagName.toLowerCase()}[placeholder="${escapeCssAttr(placeholder)}"]`;
      if (isUniqueSelector(phSel, element)) return phSel;
    }
    const relXpath = getRelativeXPath(element);
    if (relXpath && document.evaluate) {
      try {
        const result = document.evaluate(
          relXpath,
          document,
          null,
          XPathResult.FIRST_ORDERED_NODE_TYPE,
          null
        );
        if (result.singleNodeValue === element) {
          return relXpath;
        }
      } catch {
        /* fall through */
      }
    }
    return buildUniqueCssSelector(element);
  }

  function scoreSelector(element, recommendedSelector) {
    if (element.dataset?.testid || element.dataset?.cy || element.dataset?.test) return 5;
    if (recommendedSelector.startsWith('#') && element.id && !isAutoGeneratedId(element.id)) return 4;
    if (recommendedSelector.startsWith('[aria-label')) return 4;
    if (recommendedSelector.includes('[name=')) return 3;
    if (recommendedSelector.includes('.') && !recommendedSelector.startsWith('//')) return 3;
    if (recommendedSelector.includes('[placeholder')) return 2;
    if (recommendedSelector.startsWith('//')) return 2;
    return 1;
  }

  function buildSelectorInfo(element) {
    const recommendedSelector = generateBestSelector(element);
    const cssSelector = buildUniqueCssSelector(element);
    const ariaLabel = element.getAttribute('aria-label');
    const role = element.getAttribute('role');

    return {
      id: element.id || null,
      name: element.getAttribute('name') || null,
      cssSelector,
      fullCssPath: buildFullCssPath(element),
      xpath: getAbsoluteXPath(element),
      relativeXpath: getRelativeXPath(element),
      dataAttributes: getDataAttributes(element),
      ariaLabel,
      ariaRole: role,
      placeholder: element.getAttribute('placeholder') || null,
      type: element.getAttribute('type') || null,
      tagName: element.tagName,
      textContent: trimText(element.textContent),
      href: element.tagName === 'A' ? element.href : null,
      selectorReliability: scoreSelector(element, recommendedSelector),
      recommendedSelector
    };
  }

  function getActionableTarget(event) {
    let el = event.target;
    if (!(el instanceof Element)) return null;

    if (el.closest('[data-test-recorder-ignore]')) return null;

    const interactive = el.closest(
      'a, button, input, select, textarea, [role="button"], [role="link"], [onclick], [tabindex]:not([tabindex="-1"])'
    );
    if (interactive) return interactive;

    if (INTERACTIVE_TAGS.has(el.tagName)) return el;
    const role = el.getAttribute('role');
    if (role && INTERACTIVE_ROLES.has(role)) return el;

    if (event.type === 'click') {
      const style = window.getComputedStyle(el);
      if (style.cursor === 'pointer') return el;
      return null;
    }

    return el;
  }

  function describeElement(element) {
    const text = trimText(element.getAttribute('aria-label') || element.textContent || element.value, 40);
    const tag = element.tagName.toLowerCase();
    if (text) return `"${text}"`;
    if (element.id) return `#${element.id}`;
    if (element.name) return `${tag}[name="${element.name}"]`;
    return tag;
  }

  function buildDescription(action, element, value) {
    const label = describeElement(element);
    const t = typeof I18N !== 'undefined' ? I18N : null;
    if (!t) {
      switch (action) {
        case 'Click':
          return `Click ${label}`.trim();
        case 'Type':
          return `Type "${value || ''}" into ${label}`;
        default:
          return `${action} ${label}`;
      }
    }
    switch (action) {
      case 'Click':
        if (element.tagName === 'BUTTON') return t.descClickButton(label);
        if (element.tagName === 'A') return t.descClickLink(label);
        return t.descClickElement(label);
      case 'Type':
        return t.descType(value || '', label);
      case 'Select': {
        const displayVal =
          value === 'checked' ? 'ჩართული' : value === 'unchecked' ? 'გამორთული' : value || '';
        return t.descSelect(displayVal, label);
      }
      case 'Submit':
        return t.descSubmit(label);
      case 'Key':
        return t.descKey(value, label);
      case 'Navigate':
        return t.descNavigate(value || window.location.href);
      default:
        return `${t.actionLabel(action)} — ${label}`;
    }
  }

  function sendStep(step) {
    chrome.runtime.sendMessage({ type: 'ADD_STEP', step }, () => {
      if (chrome.runtime.lastError) {
        /* extension context invalidated */
      }
    });
  }

  function createTestStep(action, element, value, extra = {}) {
    stepCounter += 1;
    const selector = element ? buildSelectorInfo(element) : {
      id: null,
      name: null,
      cssSelector: 'body',
      fullCssPath: 'body',
      xpath: '/html/body',
      relativeXpath: '//body',
      dataAttributes: {},
      ariaLabel: null,
      ariaRole: null,
      placeholder: null,
      type: null,
      tagName: 'BODY',
      textContent: '',
      href: null,
      selectorReliability: 1,
      recommendedSelector: 'body'
    };

    const t = typeof I18N !== 'undefined' ? I18N : null;
    const screenshotHints = t
      ? {
          Click: t.screenshotClick,
          Type: t.screenshotType,
          Navigate: t.screenshotNavigate,
          Select: t.screenshotSelect,
          Submit: t.screenshotSubmit
        }
      : {
          Click: 'Take screenshot before clicking',
          Type: 'Take screenshot after field is filled',
          Navigate: 'Take screenshot after page loads',
          Select: 'Take screenshot after selection',
          Submit: 'Take screenshot before submit'
        };

    return {
      stepNumber: stepCounter,
      timestamp: new Date().toISOString(),
      action,
      description: extra.description || buildDescription(action, element, value),
      value: value ?? null,
      selector,
      pageUrl: window.location.href,
      pageTitle: document.title,
      isNavigation: extra.isNavigation || false,
      screenshotNote: screenshotHints[action] || (t ? t.screenshotDefault : 'Take screenshot')
    };
  }

  function recordStep(action, element, value, extra) {
    if (!isRecording) return;
    const step = createTestStep(action, element, value, extra);
    sendStep(step);
  }

  function flushPendingInput() {
    if (!pendingInputElement) return;
    const el = pendingInputElement;
    const val = pendingInputValue;
    pendingInputElement = null;
    pendingInputValue = null;
    if (val !== null && val !== undefined && String(val).length > 0) {
      recordStep('Type', el, String(val));
    }
  }

  function onClick(event) {
    if (!isRecording) return;
    const target = getActionableTarget(event);
    if (!target) return;
    flushPendingInput();
    recordStep('Click', target, null);
  }

  function onInput(event) {
    if (!isRecording) return;
    const target = event.target;
    if (!(target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement)) return;

    pendingInputElement = target;
    pendingInputValue = target.value;

    clearTimeout(inputDebounceTimer);
    inputDebounceTimer = setTimeout(() => {
      flushPendingInput();
    }, 500);
  }

  function onChange(event) {
    if (!isRecording) return;
    const target = event.target;
    if (!(target instanceof HTMLSelectElement || target instanceof HTMLInputElement)) return;

    flushPendingInput();
    const value = target.value;
    if (target instanceof HTMLSelectElement) {
      recordStep('Select', target, value);
    } else if (target.type === 'checkbox' || target.type === 'radio') {
      recordStep('Select', target, target.checked ? 'checked' : 'unchecked');
    }
  }

  function onSubmit(event) {
    if (!isRecording) return;
    const form = event.target;
    if (!(form instanceof HTMLFormElement)) return;
    flushPendingInput();
    recordStep('Submit', form, null);
  }

  function onKeydown(event) {
    if (!isRecording) return;
    if (event.key !== 'Enter' && event.key !== 'Tab') return;
    const target = event.target;
    if (!(target instanceof Element)) return;
    flushPendingInput();
    recordStep('Key', target, event.key);
  }

  function recordNavigation(newUrl) {
    if (!isRecording || newUrl === lastUrl) return;
    lastUrl = newUrl;
    stepCounter += 1;
    const step = {
      stepNumber: stepCounter,
      timestamp: new Date().toISOString(),
      action: 'Navigate',
      description: (typeof I18N !== 'undefined' ? I18N : { descNavigate: (u) => `Navigate to ${u}` }).descNavigate(newUrl),
      value: newUrl,
      selector: {
        id: null,
        name: null,
        cssSelector: 'body',
        fullCssPath: 'body',
        xpath: '/html/body',
        relativeXpath: '//body',
        dataAttributes: {},
        ariaLabel: null,
        ariaRole: null,
        placeholder: null,
        type: null,
        tagName: 'BODY',
        textContent: '',
        href: null,
        selectorReliability: 1,
        recommendedSelector: 'body'
      },
      pageUrl: newUrl,
      pageTitle: document.title,
      isNavigation: true,
      screenshotNote: typeof I18N !== 'undefined' ? I18N.screenshotNavigate : 'Take screenshot after page loads'
    };
    sendStep(step);
  }

  function checkUrlChange() {
    const href = window.location.href;
    if (href !== lastUrl) {
      recordNavigation(href);
    }
  }

  function setupNavigationDetection() {
    const observer = new MutationObserver(() => {
      checkUrlChange();
    });

    if (document.body) {
      observer.observe(document.body, { childList: true, subtree: true });
    } else {
      document.addEventListener('DOMContentLoaded', () => {
        observer.observe(document.body, { childList: true, subtree: true });
      });
    }

    const wrapHistory = (method) => {
      const original = history[method];
      return function (...args) {
        const result = original.apply(this, args);
        setTimeout(checkUrlChange, 0);
        return result;
      };
    };

    history.pushState = wrapHistory('pushState');
    history.replaceState = wrapHistory('replaceState');

    window.addEventListener('popstate', () => setTimeout(checkUrlChange, 0));
    window.addEventListener('hashchange', () => setTimeout(checkUrlChange, 0));
  }

  function startRecording() {
    isRecording = true;
    lastUrl = window.location.href;
    chrome.runtime.sendMessage({ type: 'GET_STEPS' }, (res) => {
      if (chrome.runtime.lastError) {
        stepCounter = 0;
        return;
      }
      stepCounter = res?.steps?.length || 0;
    });
    document.documentElement.setAttribute('data-test-recorder-active', 'true');
  }

  function stopRecording() {
    isRecording = false;
    flushPendingInput();
    document.documentElement.removeAttribute('data-test-recorder-active');
  }

  function notifyInjectedPageOfRecordingState(isRecording) {
    window.postMessage(
      { source: CONTENT_SCRIPT_MESSAGE_SOURCE, type: 'RECORDING_STATE', isRecording: Boolean(isRecording) },
      '*'
    );
  }

  function syncRecordingState() {
    chrome.storage.local.get(['isRecording'], (result) => {
      if (chrome.runtime.lastError) return;
      if (result.isRecording) {
        startRecording();
      } else {
        stopRecording();
      }
      notifyInjectedPageOfRecordingState(result.isRecording);
    });
  }

  window.addEventListener('message', (event) => {
    if (event.source !== window) return;
    const message = event.data;
    if (!message || message.source !== INJECTED_PAGE_MESSAGE_SOURCE) return;

    if (message.type === 'API_REQUEST' && message.apiRequest) {
      chrome.runtime.sendMessage({ type: 'ADD_API_REQUEST', apiRequest: message.apiRequest }, (response) => {
        if (chrome.runtime.lastError) {
          console.debug('[Test Recorder] Failed to forward API request:', chrome.runtime.lastError.message);
        }
      });
    }
  });

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message.type === 'RECORDING_STATE') {
      if (message.isRecording) {
        startRecording();
      } else {
        stopRecording();
      }
      notifyInjectedPageOfRecordingState(message.isRecording);
      sendResponse({ ok: true });
      return true;
    }
    if (message.type === 'GET_LOCAL_STEP_COUNT') {
      sendResponse({ count: stepCounter });
      return true;
    }
    return false;
  });

  document.addEventListener('click', onClick, true);
  document.addEventListener('input', onInput, true);
  document.addEventListener('change', onChange, true);
  document.addEventListener('submit', onSubmit, true);
  document.addEventListener('keydown', onKeydown, true);

  setupNavigationDetection();
  syncRecordingState();

  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== 'local') return;
    if (changes.isRecording) {
      if (changes.isRecording.newValue) {
        startRecording();
      } else {
        stopRecording();
      }
      notifyInjectedPageOfRecordingState(changes.isRecording.newValue);
    }
  });
})();